version: '3.4'

services:
  loadtester:
    image: ${DOCKER_REGISTRY-}loadtester
    build:
      context: .
      dockerfile: LoadTester/Dockerfile
    stdin_open: true  
    tty: true
    depends_on:
      - prometheus
      - grafana
    networks:
      - shared-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - shared-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" 
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - shared-network
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  shared-network:
    name: shared-network
    external: false

volumes:
  grafana-data:
