{
 "title": "Kafka Dashboard Copy",
 "description": "Kafka resource usage and consumer lag overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kafka_job_name",
    "label": "kafka_job_name",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate, job)"
    }
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate{job=\"$kafka_job_name\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_cluster_partition_replicascount{job=\"$kafka_job_name\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Partitions Leader Per Broker",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_cluster_Partition_ReplicasCount{instance=\"kafka:7071\", job=\"kafka\", topic=\"comments-new\"}"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_ReplicaManager_LeaderCount{job=~\"kafka\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Active Controllers",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\nkafka_controller_KafkaController_ActiveControllerCount{instance=\"kafka:7071\", job=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_BrokerTopicMetrics_BytesOut_total{instance=\"kafka:7071\", job=\"kafka\"}[2m]))by(instance)",
     "legendFormat": "Bytes Out [{{instance}}]"
    },
    {
     "expr": "sum (rate(kafka_server_BrokerTopicMetrics_BytesIn_total{instance=\"kafka:7071\", job=\"kafka\"}[2m]))by(instance)",
     "legendFormat": "Bytes In [{{instance}}]"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\nkafka_controller_KafkaController_GlobalTopicCount{instance=\"kafka:7071\", job=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Under Replicated Partitions",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\nkafka_cluster_Partition_UnderReplicated{instance=\"kafka:7071\", job=\"kafka\", topic=\"comments-new\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{job=~\"$kafka_job_name\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "description": "Offline Partitions",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_OfflinePartitionsCount{instance=\"kafka:7071\", job=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Messages In Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(topic)(increase(kafka_server_BrokerTopicMetrics_MessagesIn_total{instance=\"kafka:7071\", job=\"kafka\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(topic)(increase(kafka_server_BrokerTopicMetrics_BytesIn_total{instance=\"kafka:7071\", job=\"kafka\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(topic)(increase(kafka_server_BrokerTopicMetrics_BytesOut_total{instance=\"kafka:7071\", job=\"kafka\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_BrokerTopicMetrics_MessagesIn_total{instance=\"kafka:7071\", job=\"kafka\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(instance)(increase(\r\nkafka_server_BrokerTopicMetrics_BytesIn_total{instance=\"kafka:7071\", job=\"kafka\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(instance)(increase(\r\nkafka_server_BrokerTopicMetrics_BytesOut_total{instance=\"kafka:7071\", job=\"kafka\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka log size by topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_log_Log_Size{instance=\"kafka:7071\", job=\"kafka\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Underreplicated partitions by topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(kafka_cluster_Partition_UnderReplicated{instance=\"kafka:7071\", job=\"kafka\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Request Latency Ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(kafka_server_ZooKeeperClientMetrics_ZooKeeperRequestLatencyMs{instance=\"kafka:7071\", job=\"kafka\", quantile=\"0.50\"})by(instance)",
     "legendFormat": "Broker: {{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Expires Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (irate(kafka_server_SessionExpireListener_ZooKeeperExpires_total{instance=\"kafka:7071\", job=\"kafka\"}[1m]))by(instance)",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "ISR expands by instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(kafka_server_ReplicaManager_IsrExpands_total{instance=\"kafka:7071\", job=\"kafka\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}