version: '3.4'

services:
  comments-app-db:
    container_name: comments-app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "8082:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@123

  comments-app:
    container_name: comments-app-server
    build:
      context: .
      dockerfile: Comments-app/Dockerfile
    ports: 
      - "8080:80"
      - "8081:81"
    depends_on:
      - comments-app-db
      - kafka
    environment:
      - DB_HOST=comments-app-db
      - DB_NAME=CommentsApp
      - DB_SA_PASSWORD=password@123
      - KAFKA_HOST=kafka:9092
      - ASPNETCORE_URLS=http://0.0.0.0:80
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
